root:
  path:     /
  defaults: { _controller: AppBundle:Home:index, allowRedirect: true }

intro:
  path:     /intro
  defaults: { _controller: AppBundle:Home:index, allowRedirect: false }

stats:
  path:     /stats
  defaults: { _controller: AppBundle:Home:stats }

hub_list:
  path:     /hubs
  defaults: { _controller: AppBundle:Hubs:list, format: null }

hub_show:
  path:     /hubs/{urlKey}.{format}
  defaults: { _controller: AppBundle:Hubs:show, format: null }

player_list:
  path:     /players
  defaults: { _controller: AppBundle:Players:list, format: null }

player_show:
  path:     /players/{nickname}.{format}
  defaults: { _controller: AppBundle:Players:show, format: null }

play:
  path:     /play
  defaults: { _controller: AppBundle:Game:play }

# temporary
arrival:
  path:     /play/arrival.json
  defaults: { _controller: AppBundle:Game:arrival }

game_status:
  path:     /play/status.json
  defaults: { _controller: AppBundle:Game:status }

action_new_player:
  path:     /play/new-player.json
  defaults: { _controller: AppBundle:Game:newPlayer }

action_make_move:
  path:     /play/move.json
  defaults: { _controller: AppBundle:Game:makeMove }
